input_files:
  - "./data/source/dataset.xlsx"

output:
  dir: "./data/source_limpio/"
  format: "xlsx"

# (el resto de tu config original ...)
schema:
  mesa_de_ayuda: string
  nivel: int
  prioridad: string
  origen: string
  estado: string
  tipo: string
  fecha_creacion: datetime
  fecha_cierre: datetime
  asunto: string
  fecha_solucion: datetime
  id: string
  categoria_principal: string
  subcategoria: string
  accion: string

mappings:
  mesa_de_ayuda:
    source: "Mesa de ayuda"
    transforms:
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
      - { name: "remove_pattern", pattern: "nivel\\s*\\d+" }
  nivel:
    source: "Mesa de ayuda"
    transforms:
      - { name: "regex_extract", pattern: "nivel\\s*(\\d+)", group: 1, as_type: int }
  prioridad:
    source: "Prioridad"
    transforms:
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  origen:
    source: "Origen"
    transforms:
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  estado:
    source: "Estado"
    transforms:
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  tipo:
    source: "Tipo"
    transforms:
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  fecha_creacion:
    source: "Fecha de creación"
    transforms:
      - { name: "to_datetime", format: null }
      - { name: "to_isoformat" }
  fecha_cierre:
    source: "Fecha de cierre"
    transforms:
      - { name: "to_datetime" }
      - { name: "to_isoformat" }
  asunto:
    source: "Asunto"
    transforms:
      - { name: "trim" }
      - { name: "normalize_text", lowercase: true}
  fecha_solucion:
    source: "Fecha de solución"
    transforms:
      - { name: "to_datetime" }
      - { name: "to_isoformat" }
  id:
    source: "ID"
    transforms:
      - { name: "cast_type", to: "string" }
      - { name: "strip_leading_zeros" }
  categoria_principal:
    source: "Categoría"
    transforms:
      - { name: "split_by", delimiter: ">", index: 1 }
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  subcategoria:
    source: "Categoría"
    transforms:
      - { name: "split_by", delimiter: ">", index: 2 }
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }
  accion:
    source: "Categoría"
    transforms:
      - { name: "split_by_rest", delimiter: ">", start_index: 3, join_with: " > " }
      - { name: "normalize_text", lowercase: true, strip_accents: true, trim: true }

quality:
  duplicates:
    key: "id"
    action: "keep_latest"
    latest_by: "fecha_creacion"
  allowed_values:
    estado: ["abierto", "cerrado", "en espera", "otro"]
  null_handling:
    fill_with_null: true
